// THE WORD FOR ALL THE WORLD: Tailwind preset.
//
// Brand system v7.6, updated 2026-08-22.
// GENERATED by tools/build_ai.py from the Brand Guide. Do not edit by hand.
//
//   // tailwind.config.js
//   module.exports = { presets: [require('@theword/brand/tailwind.preset.js')] }
//
// This replaces Tailwind's default palette and type scale rather than extending
// them, so an off-brand colour is not one class away.

module.exports = {
  theme: {
    colors: {
      "midnight": "#0B1A2D",
      "word-blue": "#023D6F",
      "parchment": "#F7F3EC",
      "flame": "#F85842",
      "ember": "#C13A24",
      "white": "#FFFFFF",
      "ink": "#0B1A2D",
      "ink-muted": "rgba(11,26,45,.80)",
      "ink-soft": "rgba(11,26,45,.60)",
      "ink-faint": "rgba(11,26,45,.38)",
      "rule": "rgba(11,26,45,.18)",
      "rule-soft": "rgba(11,26,45,.10)",
      "wash": "rgba(11,26,45,.05)",
      "ink-reversed": "#F7F3EC",
      "ink-reversed-muted": "rgba(247,243,236,.75)",
      "ink-reversed-soft": "rgba(247,243,236,.55)",
      "ink-reversed-faint": "rgba(247,243,236,.38)",
      "rule-light": "rgba(247,243,236,.22)",
      "wash-light": "rgba(247,243,236,.08)",
      "success": "#5FAD56",
      "error": "#8C1D13",
      "warning": "#8A5B12",
      "outcome-ministered-light": "#005F5E",
      "outcome-ministered-dark": "#00DDDB",
      "outcome-salvation-light": "#007D4C",
      "outcome-salvation-dark": "#00C479",
      "outcome-healing-light": "#3B4100",
      "outcome-healing-dark": "#B2BE2C",
      "outcome-baptism-water-light": "#0070BD",
      "outcome-baptism-water-dark": "#9CC3FF",
      "outcome-baptism-spirit-light": "#4C3DAF",
      "outcome-baptism-spirit-dark": "#A98FFF",
      "outcome-raised-light": "#860048",
      "outcome-raised-dark": "#FF83B2",
      "progression-1-light": "#F8E4D7",
      "progression-1-dark": "#5C412F",
      "progression-2-light": "#FAD5BF",
      "progression-2-dark": "#6D462F",
      "progression-3-light": "#FBC6A9",
      "progression-3-dark": "#7F4B2F",
      "progression-4-light": "#FBB694",
      "progression-4-dark": "#924F30",
      "progression-5-light": "#FBA680",
      "progression-5-dark": "#A55231",
      "progression-6-light": "#FB956E",
      "progression-6-dark": "#B95534",
      "progression-7-light": "#FA825E",
      "progression-7-dark": "#CD5737",
      "progression-8-light": "#F96E4F",
      "progression-8-dark": "#E2583C",
      "progression-9-light": "#F85842",
      "progression-9-dark": "#F85842"
},
    fontFamily: {
      "serifDisplay": [
            "'DM Serif Display', Georgia, 'Times New Roman', serif"
      ],
      "serifText": [
            "'DM Serif Text', Georgia, 'Times New Roman', serif"
      ],
      "sans": [
            "'DM Sans', -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif"
      ]
},
    fontSize: {
      "label": [
            "12px",
            {
                  "lineHeight": "1.4"
            }
      ],
      "caption": [
            "13px",
            {
                  "lineHeight": "1.6"
            }
      ],
      "body-small": [
            "15px",
            {
                  "lineHeight": "1.65"
            }
      ],
      "body": [
            "17px",
            {
                  "lineHeight": "1.7"
            }
      ],
      "body-large": [
            "19px",
            {
                  "lineHeight": "1.65"
            }
      ],
      "title-small": [
            "22px",
            {
                  "lineHeight": "1.35"
            }
      ],
      "title": [
            "28px",
            {
                  "lineHeight": "1.25"
            }
      ],
      "title-large": [
            "34px",
            {
                  "lineHeight": "1.18"
            }
      ],
      "display-small": [
            "40px",
            {
                  "lineHeight": "1.12"
            }
      ],
      "display": [
            "52px",
            {
                  "lineHeight": "1.08"
            }
      ],
      "display-large": [
            "72px",
            {
                  "lineHeight": "1.04"
            }
      ]
},
    spacing: {
      "space-1": "4px",
      "space-2": "8px",
      "space-3": "12px",
      "space-4": "16px",
      "space-5": "24px",
      "space-6": "32px",
      "space-7": "48px",
      "space-8": "64px",
      "space-9": "96px",
      "space-10": "128px"
},
    borderRadius: {
      "radius-button": "3px",
      "radius-card": "4px",
      "radius-frame": "6px"
},
    boxShadow: {
      "flat": "none",
      "raised": "0 2px 6px rgba(11,26,45,.06)",
      "lifted": "0 10px 30px rgba(11,26,45,.10)",
      "overlay": "0 24px 60px rgba(11,26,45,.18)"
},
    screens: {
      "email": "600px",
      "page": "720px",
      "wide": "1080px"
},
    extend: {},
  },
}
