// THE WORD FOR ALL THE WORLD: design tokens.
//
// Brand system v7.7, messaging v2.0, updated 2026-08-22.
// GENERATED by tools/build_ai.py from the Brand Guide. Do not edit by hand.
//
// Prefer the CSS custom properties in brand.css wherever CSS can reach. Reach for
// these where it cannot: a canvas, a chart library, an email builder, a native app.

export const color = {
    "midnight": "#0B1A2D",
    "word-blue": "#023D6F",
    "parchment": "#F7F3EC",
    "flame": "#F85842",
    "ember": "#C13A24",
    "white": "#FFFFFF",
  } as const

export const neutral = {
    "ink": "#0B1A2D",
    "ink-muted": "rgba(11,26,45,.80)",
    "ink-soft": "rgba(11,26,45,.60)",
    "ink-faint": "rgba(11,26,45,.38)",
    "rule": "rgba(11,26,45,.18)",
    "rule-soft": "rgba(11,26,45,.10)",
    "wash": "rgba(11,26,45,.05)",
    "ink-reversed": "#F7F3EC",
    "ink-reversed-muted": "rgba(247,243,236,.75)",
    "ink-reversed-soft": "rgba(247,243,236,.55)",
    "ink-reversed-faint": "rgba(247,243,236,.38)",
    "rule-light": "rgba(247,243,236,.22)",
    "wash-light": "rgba(247,243,236,.08)",
  } as const

export const outcome = {
    "outcome-ministered": {"light": "#005F5E", "dark": "#00DDDB"},
    "outcome-salvation": {"light": "#007D4C", "dark": "#00C479"},
    "outcome-healing": {"light": "#3B4100", "dark": "#B2BE2C"},
    "outcome-baptism-water": {"light": "#0070BD", "dark": "#9CC3FF"},
    "outcome-baptism-spirit": {"light": "#4C3DAF", "dark": "#A98FFF"},
    "outcome-raised": {"light": "#860048", "dark": "#FF83B2"},
  } as const

export const progression = {
    "progression-1": {"light": "#F8E4D7", "dark": "#5C412F"},
    "progression-2": {"light": "#FAD5BF", "dark": "#6D462F"},
    "progression-3": {"light": "#FBC6A9", "dark": "#7F4B2F"},
    "progression-4": {"light": "#FBB694", "dark": "#924F30"},
    "progression-5": {"light": "#FBA680", "dark": "#A55231"},
    "progression-6": {"light": "#FB956E", "dark": "#B95534"},
    "progression-7": {"light": "#FA825E", "dark": "#CD5737"},
    "progression-8": {"light": "#F96E4F", "dark": "#E2583C"},
    "progression-9": {"light": "#F85842", "dark": "#F85842"},
  } as const

export const fontFamily = {
    "serifDisplay": "'DM Serif Display', Georgia, 'Times New Roman', serif",
    "serifText": "'DM Serif Text', Georgia, 'Times New Roman', serif",
    "sans": "'DM Sans', -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif",
  } as const

export const fontSize = {
    "label": "12px",
    "caption": "13px",
    "body-small": "15px",
    "body": "17px",
    "body-large": "19px",
    "title-small": "22px",
    "title": "28px",
    "title-large": "34px",
    "display-small": "40px",
    "display": "52px",
    "display-large": "72px",
  } as const

export const lineHeight = {
    "label": "1.4",
    "caption": "1.6",
    "body-small": "1.65",
    "body": "1.7",
    "body-large": "1.65",
    "title-small": "1.35",
    "title": "1.25",
    "title-large": "1.18",
    "display-small": "1.12",
    "display": "1.08",
    "display-large": "1.04",
  } as const

export const spacing = {
    "space-1": "4px",
    "space-2": "8px",
    "space-3": "12px",
    "space-4": "16px",
    "space-5": "24px",
    "space-6": "32px",
    "space-7": "48px",
    "space-8": "64px",
    "space-9": "96px",
    "space-10": "128px",
  } as const

export const radius = {
    "radius-button": "3px",
    "radius-card": "4px",
    "radius-frame": "6px",
  } as const

export const elevation = {
    "flat": "none",
    "raised": "0 2px 6px rgba(11,26,45,.06)",
    "lifted": "0 10px 30px rgba(11,26,45,.10)",
    "overlay": "0 24px 60px rgba(11,26,45,.18)",
  } as const

export const motion = {
    "duration-fast": "120ms",
    "duration-base": "150ms",
    "duration-slow": "300ms",
    "easing": "cubic-bezier(.2,.6,.2,1)",
  } as const

export const breakpoint = {
    "email": "600px",
    "page": "720px",
    "wide": "1080px",
  } as const

export const meta = {
  brandVersion: "7.7",
  messagingVersion: "2.0",
  updated: "2026-08-22",
  manifest: "https://brand.theword.world/ai/manifest.json",
} as const

export type ColorName = keyof typeof color
export type OutcomeName = keyof typeof outcome
export type ProgressionStep = keyof typeof progression
export type SpacingStep = keyof typeof spacing
export type TypeStep = keyof typeof fontSize
