// THE WORD FOR ALL THE WORLD: Tailwind preset.
//
// Brand system v7.2, updated 2026-08-20.
// GENERATED by tools/build_ai.py from the Brand Guide. Do not edit by hand.
//
//   // tailwind.config.js
//   module.exports = { presets: [require('@theword/brand/tailwind.preset.js')] }
//
// This replaces Tailwind's default palette and type scale rather than extending
// them, so an off-brand colour is not one class away.

module.exports = {
  theme: {
    colors: {
      "midnight": "#0B1A2D",
      "word-blue": "#023D6F",
      "parchment": "#F7F3EC",
      "flame": "#F85842",
      "ember": "#C13A24",
      "white": "#FFFFFF",
      "ink": "#0B1A2D",
      "ink-muted": "rgba(11,26,45,.80)",
      "ink-soft": "rgba(11,26,45,.60)",
      "ink-faint": "rgba(11,26,45,.38)",
      "rule": "rgba(11,26,45,.18)",
      "rule-soft": "rgba(11,26,45,.10)",
      "wash": "rgba(11,26,45,.05)",
      "ink-reversed": "#F7F3EC",
      "ink-reversed-muted": "rgba(247,243,236,.75)",
      "ink-reversed-soft": "rgba(247,243,236,.55)",
      "rule-light": "rgba(247,243,236,.22)",
      "wash-light": "rgba(247,243,236,.08)",
      "success": "#5FAD56",
      "error": "#8C1D13",
      "warning": "#8A5B12"
},
    fontFamily: {
      "serifDisplay": [
            "'DM Serif Display', Georgia, 'Times New Roman', serif"
      ],
      "serifText": [
            "'DM Serif Text', Georgia, 'Times New Roman', serif"
      ],
      "sans": [
            "'DM Sans', -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif"
      ]
},
    fontSize: {
      "label": [
            "12px",
            {
                  "lineHeight": "1.4"
            }
      ],
      "caption": [
            "13px",
            {
                  "lineHeight": "1.6"
            }
      ],
      "body-small": [
            "15px",
            {
                  "lineHeight": "1.65"
            }
      ],
      "body": [
            "17px",
            {
                  "lineHeight": "1.7"
            }
      ],
      "body-large": [
            "19px",
            {
                  "lineHeight": "1.65"
            }
      ],
      "title-small": [
            "22px",
            {
                  "lineHeight": "1.35"
            }
      ],
      "title": [
            "28px",
            {
                  "lineHeight": "1.25"
            }
      ],
      "title-large": [
            "34px",
            {
                  "lineHeight": "1.18"
            }
      ],
      "display-small": [
            "40px",
            {
                  "lineHeight": "1.12"
            }
      ],
      "display": [
            "52px",
            {
                  "lineHeight": "1.08"
            }
      ],
      "display-large": [
            "72px",
            {
                  "lineHeight": "1.04"
            }
      ]
},
    spacing: {
      "space-1": "4px",
      "space-2": "8px",
      "space-3": "12px",
      "space-4": "16px",
      "space-5": "24px",
      "space-6": "32px",
      "space-7": "48px",
      "space-8": "64px",
      "space-9": "96px",
      "space-10": "128px"
},
    borderRadius: {
      "radius-button": "3px",
      "radius-card": "4px",
      "radius-frame": "6px"
},
    boxShadow: {
      "flat": "none",
      "raised": "0 2px 6px rgba(11,26,45,.06)",
      "lifted": "0 10px 30px rgba(11,26,45,.10)",
      "overlay": "0 24px 60px rgba(11,26,45,.18)"
},
    screens: {
      "email": "600px",
      "page": "720px",
      "wide": "1080px"
},
    extend: {},
  },
}
