#!/usr/bin/env python3
"""Download the three approved families from Google Fonts and self-host them.

    python3 tools/fetch_fonts.py

Run this by hand, not in CI. It needs the network; the build does not. The
downloaded files and the stylesheet it writes are committed, so the portal, the
apps, and anything else that links assets/fonts/fonts.css render the real faces
with no third-party request and no layout shift.

DM Serif Display, DM Serif Text, and DM Sans are licensed under the SIL Open
Font License 1.1, which permits redistribution. The license ships alongside the
files, which is what the OFL asks for in return.
"""

from __future__ import annotations

import os
import re
import sys
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "assets", "fonts")

# A modern browser UA, or Google serves the truetype fallback instead of woff2.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

FAMILIES = "family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400;1,9..40,700&family=DM+Serif+Display:ital@0;1&family=DM+Serif+Text:ital@0;1"
CSS_URL = f"https://fonts.googleapis.com/css2?{FAMILIES}&display=swap"

# The portal is read worldwide and the ministry works across Africa and Europe.
# latin-ext carries the accented characters those place names need.
KEEP_SUBSETS = {"latin", "latin-ext"}

LICENSE_URL = "https://raw.githubusercontent.com/googlefonts/dm-fonts/main/OFL.txt"


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as fh:
        return fh.read()


def main() -> int:
    os.makedirs(OUT, exist_ok=True)
    css = get(CSS_URL).decode("utf-8")

    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    if not blocks:
        print("No @font-face blocks came back. Has the css2 response format changed?", file=sys.stderr)
        return 2

    out_rules: list = []
    downloaded: dict = {}
    by_url: dict = {}

    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        weight = re.search(r"font-weight:\s*([\d\s]+);", block).group(1).strip()
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)

        # DM Sans is a variable font: every weight of a given style and subset is
        # served from the same file, so eight identical copies would otherwise be
        # committed. Name by family, style, and subset, and keep the weight in the
        # name only if the bytes actually differ.
        slug = family.lower().replace(" ", "-")
        name = f"{slug}-{style}-{subset}.woff2"
        data = by_url.get(url)
        if data is None:
            data = by_url[url] = get(url)
        if name in downloaded and downloaded[name] != data:
            name = f"{slug}-{style}-{weight.replace(' ', '-')}-{subset}.woff2"
        if name not in downloaded:
            downloaded[name] = data
            print(f"  {name}  {len(data):,} bytes")

        rule = block
        rule = re.sub(r"url\(https://[^)]+\)", f"url('/assets/fonts/{name}')", rule)
        out_rules.append(f"/* {family} {style} {weight}, {subset} */\n{rule}")

    for name, data in downloaded.items():
        with open(os.path.join(OUT, name), "wb") as fh:
            fh.write(data)

    try:
        license_text = get(LICENSE_URL).decode("utf-8")
    except Exception:
        license_text = (
            "The DM font families are licensed under the SIL Open Font License 1.1.\n"
            "Full text: https://openfontlicense.org\n"
        )
    with open(os.path.join(OUT, "OFL.txt"), "w", encoding="utf-8") as fh:
        fh.write(license_text)

    header = (
        "/* THE WORD FOR ALL THE WORLD: the three approved families, self-hosted.\n"
        " *\n"
        " * GENERATED by tools/fetch_fonts.py. Do not edit by hand.\n"
        " *\n"
        " * DM Serif Display, DM Serif Text, and DM Sans, under the SIL Open Font\n"
        " * License 1.1 (see OFL.txt beside this file). Linking this stylesheet\n"
        " * loads the faces this system uses and nothing it does not, with no\n"
        " * request to a third party and no layout shift on first paint.\n"
        " *\n"
        " * Brand Guide section 04 governs how they are set.\n"
        " */\n\n"
    )
    with open(os.path.join(OUT, "fonts.css"), "w", encoding="utf-8") as fh:
        fh.write(header + "\n\n".join(out_rules) + "\n")

    print(f"\n{len(downloaded)} font files and fonts.css written to assets/fonts/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
